language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
install:
  - npm install
env:
  global:
  - PGPORT=5432
  - NODE_ENV=test

before_script:
  - psql -c 'create database way_farer_test;' -U postgres
  - npm run build
script:
  - npm run test
after_script:
  - npm run coverage

notifications:
  - email: false
